// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZsxcnKL579Jp83gl0c_DO-mKl6UeuV2k',
    appId: '1:795571246830:web:9cae16225153ea86e645ff',
    messagingSenderId: '795571246830',
    projectId: 'bootstrap-55f24',
    authDomain: 'bootstrap-55f24.firebaseapp.com',
    storageBucket: 'bootstrap-55f24.appspot.com',
    measurementId: 'G-N5BYN7RM8H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEHqpHiW2DVd3AusAvcnESskQnQOFCtgY',
    appId: '1:795571246830:android:5f6e4b567ef66059e645ff',
    messagingSenderId: '795571246830',
    projectId: 'bootstrap-55f24',
    storageBucket: 'bootstrap-55f24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmpP8qC4JuImNLVIy5v8Sp7qydPtStmL4',
    appId: '1:795571246830:ios:92bccaf9b335ad9ee645ff',
    messagingSenderId: '795571246830',
    projectId: 'bootstrap-55f24',
    storageBucket: 'bootstrap-55f24.appspot.com',
    iosBundleId: 'com.example.bootstrap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmpP8qC4JuImNLVIy5v8Sp7qydPtStmL4',
    appId: '1:795571246830:ios:92bccaf9b335ad9ee645ff',
    messagingSenderId: '795571246830',
    projectId: 'bootstrap-55f24',
    storageBucket: 'bootstrap-55f24.appspot.com',
    iosBundleId: 'com.example.bootstrap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZsxcnKL579Jp83gl0c_DO-mKl6UeuV2k',
    appId: '1:795571246830:web:99b26bcd5035cab1e645ff',
    messagingSenderId: '795571246830',
    projectId: 'bootstrap-55f24',
    authDomain: 'bootstrap-55f24.firebaseapp.com',
    storageBucket: 'bootstrap-55f24.appspot.com',
    measurementId: 'G-F1YCGYJLCT',
  );
}
